package x_o;

import java.util.*;
import javax.swing.JButton;

/**
 * Basel Hazre 
 * Abdalrhman Alzhrani 
 * Faris Alghamdi
 * Samer Almalky
 *
 */
public class X_O extends javax.swing.JFrame {

    public final int SIZE = 4; // The size of board 
    public char PLAYER; // Human
    public char AI; // Computer
    public int nodesExplored = 0;   //Performance calculation
    char[][] board = new char[4][4]; // Create a 2D array of characters to act as the 4x4 game grid
    JButton[][] buttonGrid = new JButton[4][4];// Create a 2D array of button 
    public int level;

    public X_O() {

        initComponents();
        // match evry button to array
        buttonGrid[0][0] = btn00;
        buttonGrid[0][1] = btn01;
        buttonGrid[0][2] = btn02;
        buttonGrid[0][3] = btn03;
        buttonGrid[1][0] = btn10;
        buttonGrid[1][1] = btn11;
        buttonGrid[1][2] = btn12;
        buttonGrid[1][3] = btn13;
        buttonGrid[2][0] = btn20;
        buttonGrid[2][1] = btn21;
        buttonGrid[2][2] = btn22;
        buttonGrid[2][3] = btn23;
        buttonGrid[3][0] = btn30;
        buttonGrid[3][1] = btn31;
        buttonGrid[3][2] = btn32;
        buttonGrid[3][3] = btn33;

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                board[i][j] = '-';
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn03 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        Performance = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn00.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn01.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        btn02.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn03.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03ActionPerformed(evt);
            }
        });

        btn10.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn13.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn20.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btn21.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn22.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        btn23.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });

        btn30.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });

        btn31.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });

        btn32.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });

        btn33.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });

        Performance.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Performance.setPreferredSize(new java.awt.Dimension(90, 80));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Performance, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(Performance, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed
        playerMove(3, 3, btn33);
    }//GEN-LAST:event_btn33ActionPerformed

    private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed
        playerMove(3, 2, btn32);
    }//GEN-LAST:event_btn32ActionPerformed

    private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed
        playerMove(3, 1, btn31);
    }//GEN-LAST:event_btn31ActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed
        playerMove(3, 0, btn30);
    }//GEN-LAST:event_btn30ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        playerMove(2, 3, btn23);
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        playerMove(2, 2, btn22);
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        playerMove(2, 1, btn21);
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        playerMove(2, 0, btn20);
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        playerMove(1, 3, btn13);
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        playerMove(1, 2, btn12);
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        playerMove(1, 1, btn11);
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        playerMove(1, 0, btn10);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03ActionPerformed
        playerMove(0, 3, btn03);
    }//GEN-LAST:event_btn03ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        playerMove(0, 2, btn02);
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        playerMove(0, 1, btn01);
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        playerMove(0, 0, btn00);

    }//GEN-LAST:event_btn00ActionPerformed
    private void playerMove(int r, int c, JButton btn) {

        //  Check if there is A character already
        if (board[r][c] == '-') {
            board[r][c] = PLAYER; // update the array
            btn.setText(String.valueOf(PLAYER)); // update the button in UI
//            btn.setEnabled(false); // Disable button
            updateUI();

            if (checkWin(board, PLAYER)) { // Check if placing that last caused the human to win the game

                javax.swing.JOptionPane.showMessageDialog(this, "You win!");// Print victory message
            } else {
                AIMove();// call Ai method
            }
        }
    }
    // Computer's turn (AI using IDDFS)

    private void AIMove() {
        long startTime = System.currentTimeMillis();// Record the exact current time in milliseconds to measure AI speed
        board = iddfs(board);// Call the IDDFS algorithm to calculate the best move, which returns the new board state
        long endTime = System.currentTimeMillis();// Record the exact time again after the AI finishes its calculation
        Performance.setText(" time spend:" + (endTime - startTime) + " ms" + "\n Nodes Explored:" + nodesExplored);// print informition of Performance

        updateUI();
        if (checkWin(board, AI)) { // Check if the AI's calculated move caused the AI  to win the game

            javax.swing.JOptionPane.showMessageDialog(this, "You loss!");// Print loss message
            return;

        }
        if (isFull(board)) {// Check if the board full 
            javax.swing.JOptionPane.showMessageDialog(this, "it's Draw!!");// Print draw message
        }
    }

    private void updateUI() {
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                if (board[i][j] == 'X') {
                    buttonGrid[i][j].setForeground(java.awt.Color.BLUE);
                } else if (board[i][j] == 'O') {
                    buttonGrid[i][j].setForeground(java.awt.Color.RED);

                }
                // Update the text displayed on the button from the array
                buttonGrid[i][j].setText(String.valueOf(board[i][j]));

            }

        }
    }

    // The IDDFS (Iterative Deepening Depth-First Search) algorithm
    public char[][] iddfs(char[][] currentBoard) {
        nodesExplored = 0; // Reset nodes count for each move to analyze performance
        char[][] bestBoard = null;

        // Iteratively increase the search depth from 1 up to 6
        for (int depth = 1; depth <= level; depth++) {
            int bestScore = Integer.MIN_VALUE; // Initialize best score to the lowest possible value to find the maximum
            List<char[][]> moves = getPossibleMoves(currentBoard, AI);// Generate all possible child nodes (neighboring boards) for the AI

            for (char[][] move : moves) {
                // Call DLS to get the heuristic score (int) for the current move
                int currentScore = dls(move, depth - 1, false); // We pass 'false' because the next turn is for the Minimizing player (human)

                if (currentScore > bestScore) {  // If this move yields a better score than the current best, update it
                    bestScore = currentScore;
                    bestBoard = move; // Store the board state associated with the best score
                }
            }
        }
        return bestBoard;  // Return the optimal move found within the depth limits
    }

    // Heuristic evaluation function to assign scores to board states
    public int evaluate(char[][] board) {
        if (checkWin(board, AI)) {
            return 100; // Return +100 if the AI wins (Maximizing goal)
        }
        if (checkWin(board, PLAYER)) {
            return -100;  // Return -100 if the player wins (Minimizing goal)
        }
        return 0;   // Return 0 if the state is neutral (No winner yet)
    }

// Recursive DLS function to explore the game tree up to a given limit
    public int dls(char[][] board, int limit, boolean isMaximizing) {
        nodesExplored++; // Increment the counter to track time complexity and performance

        int score = evaluate(board); // Calculate the score for the current board state
        // Termination condition: If someone won, or the depth limit is reached
        if (score != 0 || limit == 0) {
            return score;// Return the terminal score (int)
        }

        if (isMaximizing) {
            int bestScore = Integer.MIN_VALUE; // AI's turn: Aim for the maximum possible score
            for (char[][] move : getPossibleMoves(board, AI)) {
                int currentScore = dls(move, limit - 1, false);  // Recursive call with decreasing limit and switching to the Player's turn
                bestScore = Math.max(bestScore, currentScore);
            }
            return bestScore;// Return the best score 
        } else {
            int bestScore = Integer.MAX_VALUE; // Human's turn: The AI assumes the human will aim for the minimum score
            for (char[][] move : getPossibleMoves(board, PLAYER)) {
                int currentScore = dls(move, limit - 1, true);// Recursive call with decreasing limit and switching to the AI's turn
                bestScore = Math.min(bestScore, currentScore);
            }
            return bestScore; // Return the best score 
        }
    }

    // Method to generate all possible next moves (Neighboring nodes in the Graph)
    public List<char[][]> getPossibleMoves(char[][] board, char p) {
        List<char[][]> moves = new ArrayList<>(); // Create a list to store the valid board states (future states)
        // Iterate through the 4x4 grid (rows and columns)
        for (int i = 0; i < SIZE; i++) {
            for (int j = 0; j < SIZE; j++) {
                // Check if the current cell is empty (marked with '-')
                if (board[i][j] == '-') {
                    char[][] newBoard = copyBoard(board); // Create a deep copy of the board to avoid modifying the original state
                    newBoard[i][j] = p; // Place the current player's marker (AI or Player) in the empty cell
                    moves.add(newBoard); // Add this new board state as a neighbor (potential path in the game tree)
                }
            }
        }
        return moves;  // Return the list of all legal moves (Adjacency List equivalent in Graph Theory)
    }

    // Check for win (horizontal, vertical, diagonal)
    public boolean checkWin(char[][] b, char p) { // Method that takes a board 'b' and a player 'p', returning true if 'p' has won
        for (int i = 0; i < SIZE; i++) {// Loop 4 times (from 0 to 3) to check every single row and column
            if (allSame(b[i][0], b[i][1], b[i][2], b[i][3], p)) {
                return true;// Check row 'i': if all 4 spots in this row belong to player 'p', return true (win)
            }
            if (allSame(b[0][i], b[1][i], b[2][i], b[3][i], p)) {
                return true;// Check column 'i': if all 4 spots in this column belong to player 'p', return true (win)
            }
        }
        if (allSame(b[0][0], b[1][1], b[2][2], b[3][3], p)) {
            return true; // Check the main diagonal (top-left to bottom-right): if all 4 spots match, return true
        }
        if (allSame(b[0][3], b[1][2], b[2][1], b[3][0], p)) {
            return true; // Check the anti-diagonal (top-right to bottom-left): if all 4 spots match, return true
        }
        return false;// If the code reaches here, no winning lines were found, so return false (no one has won yet)
    }

    // Method to cheek draw state
    public boolean isFull(char[][] b) {
        // Iterate through the grid (rows and columns)
        for (int i = 0; i < SIZE; i++) {
            for (int j = 0; j < SIZE; j++) {
                if (b[i][j] == '-') // Check if the current cell is empty (marked with '-')
                {
                    return false;// it mean there is space
                }
            }
        }
        return true; // it mean there is'n space

    }

    // Method to check if the all is the same character
    private static boolean allSame(char c1, char c2, char c3, char c4, char p) {
        return c1 == p && c2 == p && c3 == p && c4 == p;
    }

    // Method to create a deep copy of the board to prevent reference issues
    public char[][] copyBoard(char[][] b) {
        char[][] newB = new char[SIZE][SIZE]; // Initialize a new board with the same size
        for (int i = 0; i < SIZE; i++) {
            newB[i] = b[i].clone();// Loop through each row and use .clone() to copy the array content, not the reference
        }
        return newB;// Return the newly created independent board state
    }

    public static void main(String args[]) {
        // Define the character selection
        Object[] options = {"Play as X", "Play as O"};
        int selection = -1;
        // Force the user to choose a character (prevent closing the dialog)
        while (selection == -1) {
            selection = javax.swing.JOptionPane.showOptionDialog(
                    null,
                    "Welcome to X_O game 4x4 (Tic-Tac-Toe) \nChoose your character:",
                    "Game Setup",
                    javax.swing.JOptionPane.DEFAULT_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null, options, options[0]);
            // Trigger a beep sound if the user tries to exit without selecting
            if (selection == -1) {
                java.awt.Toolkit.getDefaultToolkit().beep();
            }
        }
        // Define the difficulty levels (Search Depth for AI)
        Object[] level = {"Esay", "Medium", "Hard"};
        int choice = -1;
        // Force the user to choose a difficulty level
        while (choice == -1) {
            choice = javax.swing.JOptionPane.showOptionDialog(null, "choose a level", "",
                    javax.swing.JOptionPane.DEFAULT_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null, level, level[0]);
            // Trigger a beep sound if the user tries to exit without selecting
            if (choice == -1) {
                java.awt.Toolkit.getDefaultToolkit().beep();
            }
        }
        // Create effective final variables to be used inside the anonymous inner class
        int tempselection = selection;
        int tempchoice = choice;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                X_O game = new X_O();  // Initialize the game object
                // Set the AI search depth based on the selected level
                if (tempchoice == 0) {
                    game.level = 1;
                } else if (tempchoice == 1) {
                    game.level = 3;
                } else {
                    game.level = 6;
                }
                // Assign players based on user selection
                if (tempselection == 1) {
                    game.PLAYER = 'O';
                    game.AI = 'X';
                } else {
                    game.PLAYER = 'X';
                    game.AI = 'O';
                }

                game.setVisible(true);// Make the game board visible to the user
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea Performance;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn03;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
